const weightLiftingArray = [
    "Ab Rollouts",
    "Arnold Press",
    "Barbell Bench Press",
    "Battle Ropes",
    "Bent-Over Rows",
    "Bicep Curls",
    "Bicycle Crunches",
    "Bulgarian Split Squats",
    "Burpees",
    "Cable Crossovers",
    "Cable Woodchoppers",
    "Calf Raises",
    "Chest Fly",
    "Chin-Ups",
    "Clean and Press",
    "Concentration Curls",
    "Crunches",
    "Deadlifts",
    "Decline Bench Press",
    "Dumbbell Bench Press",
    "Face Pulls",
    "Farmer's Walk",
    "Front Raises",
    "Front Squats",
    "Hammer Curls",
    "Hanging Leg Raises",
    "Incline Bench Press",
    "Kettlebell Swings",
    "Lat Pulldowns",
    "Lateral Raises",
    "Leg Curls",
    "Leg Extensions",
    "Leg Press",
    "Leg Raises",
    "Lunges",
    "Overhead Shoulder Press",
    "Overhead Tricep Extensions",
    "Pec Deck Machine",
    "Pendlay Rows",
    "Planks",
    "Preacher Curls",
    "Pull-Ups",
    "Push-Ups",
    "Reverse Fly",
    "Russian Twists",
    "Seated Cable Rows",
    "Shrugs",
    "Single-Arm Dumbbell Rows",
    "Skull Crushers",
    "Snatch",
    "Squats",
    "Stiff-legged Deadlifts",
    "T-Bar Rows",
    "Thrusters",
    "Tricep Dips",
    "Tricep Pushdowns",
    "Turkish Get-Up",
    "Upright Rows",
];

export default weightLiftingArray;
