const weightLiftingArray = [
    "Barbell Bench Press",
    "Dumbbell Bench Press",
    "Incline Bench Press",
    "Decline Bench Press",
    "Chest Fly",
    "Cable Crossovers",
    "Push-Ups",
    "Pec Deck Machine",
    "Pull-Ups",
    "Chin-Ups",
    "Lat Pulldowns",
    "Bent-Over Rows",
    "T-Bar Rows",
    "Seated Cable Rows",
    "Deadlifts",
    "Single-Arm Dumbbell Rows",
    "Overhead Shoulder Press",
    "Lateral Raises",
    "Front Raises",
    "Upright Rows",
    "Shrugs",
    "Arnold Press",
    "Reverse Fly",
    "Face Pulls",
    "Bicep Curls",
    "Hammer Curls",
    "Tricep Dips",
    "Tricep Pushdowns",
    "Skull Crushers",
    "Concentration Curls",
    "Preacher Curls",
    "Overhead Tricep Extensions",
    "Squats",
    "Leg Press",
    "Lunges",
    "Leg Curls",
    "Leg Extensions",
    "Calf Raises",
    "Bulgarian Split Squats",
    "Crunches",
    "Planks",
    "Russian Twists",
    "Leg Raises",
    "Bicycle Crunches",
    "Cable Woodchoppers",
    "Hanging Leg Raises",
    "Ab Rollouts",
    "Clean and Press",
    "Snatch",
    "Thrusters",
    "Kettlebell Swings",
    "Burpees",
    "Turkish Get-Up",
    "Farmer's Walk",
    "Battle Ropes",
    "Stiff-legged Deadlifts",
    "Pendlay Rows",
    "Front Squats",
  ];
  
export default weightLiftingArray;